#github action for all python files being push to the main branch

#Author: Eng. Michael Kofi Armah
#Date Created: 11/05/22


name: PEP8 requirements

on: 
  push: #action runs on push events that target the main and api branches
    branches:
      - api
      - main
      
  pull_request: #action runs on pull_requests that runs on the main branch
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest #runs on ubuntu's latest os

    steps:
    - uses: actions/checkout@v3
    - name: Python Set up 
      uses: actions/setup-python@v3 
      with:
        python-version: '3.10' #python version to run on | currently the latest version
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install autopep8
        
    - name: Autop8p
      run: |
        autopep8 --in-place --aggressive --aggressive $(git ls-files '*.py')
        
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
